### ISSUE TITLE
Lumen?

### ISSUE THREAD

**Issue by Sjoerrdd** [orchidsoftware/web-socket#19]
Hello,
Does this work with [Lumen](https://lumen.laravel.com/)?

**Comment by tabuna** [comment]
Hi, I did not test with lumen, you can add the right-hand one yourself.

**Comment by Sjoerrdd** [comment]
Sadly enough, it doesn't work

**Comment by tabuna** [comment]
Can you add support?

**Comment by Sjoerrdd** [comment]
I'll try
